# Development Docker Compose override
# Runs backend and frontend with hot reloading, no Nginx
services:
  backend:
    build: ./backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - DATABASE_PATH=/data/sqlite/database.db
    volumes:
      - ./backend:/app
      - ./Original Docs data and example:/data
      - lms_sqlite_data:/data/sqlite
    command: flask run --host=0.0.0.0 --port=6001
    ports:
      - "6001:6001"

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_BASE=http://localhost:6001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host --port 6002
    stdin_open: true
    tty: true
    ports:
      - "6002:6002"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=training_lms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  lms_sqlite_data:
